#include "newcomp/newcompiler.h"
#include <stdarg.h>
#include <string.h>

void debug_print(const char* text) {
    if (DEBUG_ACTIONS != 1) {
        return;
    }

    fprintf(stderr, "\033[1;32m[Compiler]\033[0m: %s\n", text);
}

void debug_print_formatted(const char* format, ...) {
    char buffer[512];
    
    va_list args;
    va_start(args, format);
    vsnprintf(buffer, sizeof(buffer), format, args);
    va_end(args);
    
    debug_print(buffer); 
}


void allocate_const_pool_if_full(Program* program) {
    if (program->constant_counter < program->constant_limit) {
        return;
    }

    if (program->constant_limit <= 0) {
        program->constant_limit = 10;
    }

    program->constant_limit *= 2;

    Constant* reallocated = realloc(program->constants, program->constant_limit * sizeof(Constant));
    if (reallocated == NULL) {
        fprintf(stderr, "Could not reallocate program constants memory\n");
        exit(1);
    }
    
    program->constants = reallocated;
}

void allocate_program_bytes_if_full(Program* program) {
    if (program->byte_counter < program->byte_limit) {
        return;
    }

    if (program->byte_limit <= 0) {
        program->byte_limit = 10;
    }

    program->byte_limit *= 2;

    uint8_t* reallocated_bytes = realloc(program->bytes, program->byte_limit * sizeof(*program->bytes));
    if (reallocated_bytes == NULL) {
        fprintf(stderr, "Could not reallocate program constants memory\n");
        exit(1);
    }
    
    program->bytes = reallocated_bytes;
}

void emit_byte(Program* program, uint8_t byte) {
    allocate_program_bytes_if_full(program);
    program->bytes[program->byte_counter] = byte;
    program->byte_counter++;
}

void print_opcode(uint8_t op) {
    switch (op) {
        case OP_VOID:
            printf("NO_OP ");
            break;
        case OP_LOAD_CONST:
            printf("LOAD_CONST ");
            break;
        case OP_STORE_LOCAL:
            printf("STORE_LOCAL ");
            break;
        case OP_LOAD_LOCAL:
            printf("LOAD_LOCAL ");
            break;
        case OP_ADD:
            printf("OP_ADD\n");
            break;
        case OP_SUB:
            printf("OP_SUB\n");
            break;
        case OP_MUL:
            printf("OP_MUL\n");
            break;
        case OP_DIV:
            printf("OP_DIV\n");
            break;
    }
}

void print_compiled_program(Program* program) {
    printf("\n===== GENERATED BYTECODE ======\n");
    for (int i = 0; i < program->byte_counter; i++) {
        uint8_t byte_up = program->bytes[i];
        print_opcode(byte_up);
        if (byte_up == OP_LOAD_CONST || byte_up == OP_LOAD_LOCAL || byte_up == OP_STORE_LOCAL) {
            i++;
            printf("%d\n", program->bytes[i]);
        }
    }
}

uint16_t get_symbol_index(Program* program, const char* symbol) {
    for (int i = 0; i < program->symbol_table.count; i++) {
        if (strcmp(program->symbol_table.symbols[i].name, symbol) == 0) {
            return (uint16_t) i;
        }
    }

    fprintf(stderr, "Undefined symbol: %s", symbol);
    exit(1);
} 

uint16_t push_symbol(Program* program, const char* symbol) {
    if (program->symbol_table.count >= MAX_SYMBOL_COUNT) {
        fprintf(stderr, "Program exceeded the maximum amount of symbols\n");
        exit(1);
    }

    for (int i = 0; i < program->symbol_table.count; i++) {
        if (strcmp(program->symbol_table.symbols[i].name, symbol) == 0) {
            fprintf(stderr, "Redefining existing symbol %s\n", symbol);
            exit(1);
        }
    }

    Symbol new_symbol = {
        .name = symbol,
        .index = program->symbol_table.count,
    };

    program->symbol_table.symbols[program->symbol_table.count] = new_symbol;

    return program->symbol_table.count++;
}

void emit_word(Program* program, uint16_t word) {
    emit_byte(program, (word >> 8) & 0xFF);
    emit_byte(program, word & 0xFF);
}

uint32_t push_constant(Program* program, Constant constant_val) {
    allocate_const_pool_if_full(program);
    program->constants[program->constant_counter] = constant_val;
    return program->constant_counter++;
}

Program* init_program() {
    Program* new_program = malloc(sizeof(Program));
    new_program->constant_counter = 0;
    new_program->byte_counter = 0;
    new_program->constant_limit = 10;
    new_program->byte_limit = 10;
    new_program->constants = malloc(new_program->constant_limit * sizeof(Constant));
    new_program->bytes = malloc(new_program->byte_limit * sizeof(uint8_t));
    new_program->symbol_table.count = 0;

    return new_program;
}

OpCode opcode_for_op(const char* op) {
    if (strcmp(op, "+") == 0) { return OP_ADD; }
    if (strcmp(op, "-") == 0) { return OP_SUB; }
    if (strcmp(op, "/") == 0) { return OP_DIV; }
    if (strcmp(op, "*") == 0) { return OP_MUL; }

    return OP_VOID;
}

uint32_t compile_expr(Program* program, Expression* expr) {
    if (expr == NULL) return 0;

    switch (expr->type) {
        case EXPR_NUMBER: {
            Constant new_constant = {
                .type = N_CONST_NUMBER,
                .as.number = expr->data.value,
            };

            uint32_t const_pointer = push_constant(program, new_constant);
            debug_print_formatted("Pushed Number \033[1;34m[%f]\033[0m to the constant pool \033[1;35m[idx=%d]\033[0m", expr->data.value, const_pointer);

            emit_byte(program, OP_LOAD_CONST);
            emit_byte(program, (uint8_t) const_pointer); 

            return const_pointer;
        }

        case EXPR_BINARY_OPERATOR: {
            Expression* left = expr->data.operation.left;
            Expression* right = expr->data.operation.right;

            compile_expr(program, left);
            compile_expr(program, right);
            
            OpCode operation = opcode_for_op(expr->data.operation.op);
            if (operation == OP_VOID) {
                fprintf(stderr, "Operation [%s] not implemented\n", expr->data.operation.op);
                exit(1);
            }
            
            emit_byte(program, operation);

            break;
        }

        case EXPR_BOOL: {
            debug_print("Pushing a boolean to the constant pool");
            break;
        }

        case EXPR_NAME: {
            uint16_t symbol_index = get_symbol_index(program, expr->data.name);
            emit_byte(program, OP_LOAD_LOCAL);
            emit_byte(program, (uint8_t) symbol_index);

            return symbol_index;
        }

        case EXPR_DEFINE: {
            Expression* def_body = expr->data.define_body;
            Expression* assign_name = def_body->data.assign.name;
            uint16_t symbol_index = push_symbol(program, assign_name->data.name);

            compile_expr(program, def_body);
            break;
        }

        case EXPR_ASSIGN: {
            Expression* assign_value = expr->data.assign.value;
            const char* assign_name = expr->data.assign.name->data.name;
            uint16_t stored_symbol_index = get_symbol_index(program, assign_name);
            compile_expr(program, assign_value);
            
            emit_byte(program, OP_STORE_LOCAL);
            emit_byte(program, (uint8_t) stored_symbol_index);

            break;
        }

        default: {
            debug_print("A different expression appeared, type:");
            display_expression(expr);
            break;
        }
    }

    return 0;
}

void write_to_file(const char* output, Program* program) {

}

int compile_program(const char* file_name) {
    ParsedProgram* program_expressions = parse_file_expressions(file_name);
    if (program_expressions == NULL) {
        fprintf(stderr, "Could not parse program expressions, compilation terminated.\n");

        return 1;
    }

    Program* program_result = init_program();
    for (int expr_idx = 0; expr_idx < program_expressions->expression_count; expr_idx++) {
        Expression* expr = program_expressions->expressions[expr_idx];
        compile_expr(program_result, expr);
        free(expr);
    }

    free_tokens(program_expressions->tokens, program_expressions->token_count);
    free(program_expressions);
    print_compiled_program(program_result);

    return 0;
};